version: "3"

services:
    gitlab:
        image: 'gitlab/gitlab-ee:latest'
        restart: unless-stopped
        hostname: 'gitlab.ci.local'
        domainname: 'gitlab.ci.local'
        environment: 
            GITLAB_OMNIBUS_CONFIG: |
                external_url 'http://gitlab.ci.local'
                # other gitlab.rb configurations
        ports:
            - "127.0.0.1:80:80"
            - "127.0.0.1:443:443"
            - "127.0.0.1:4422:22"
        volumes:
            - '$GITLAB_HOME/config:/etc/gitlab'
            - '$GITLAB_HOME/logs:/var/log/gitlab'
            - '$GITLAB_HOME/data:/var/opt/gitlab'
    sonar:
        image: sonarqube:community
        hostname: 'sonar.ci.local'
        domainname: 'sonar.ci.local'
        depends_on: 
            - 'db'
        environment: 
            SONAR_JDBC_URL: jdbc:postgresql://db:5432/sonar
            SONAR_JDBC_USERNAME: sonar
            SONAR_JDBC_PASSWORD: sonar
        volumes:
            - $SONAR_HOME/data:/opt/sonarqube/data
            - $SONAR_HOME/extensions:/opt/sonarqube/extensions
            - $SONAR_HOME/logs:/opt/sonarqube/logs
        ports:
            - "127.0.0.1:9000:9000"
    db:
        image: postgres:12
        environment: 
            POSTGRES_USER: sonar
            POSTGRES_PASSWORD: sonar
        volumes:
            - $POSTGRESQL_HOME:/var/lib/postgresql
