version: "3"

services:
    sonar:
        image: sonarqube:community
        restart: unless-stopped
        hostname: 'sonar.ci.local'
        domainname: 'sonar.ci.local'
        depends_on: 
            - 'db'
        environment: 
            SONAR_JDBC_URL: jdbc:postgresql://db:5432/sonar
            SONAR_JDBC_USERNAME: sonar
            SONAR_JDBC_PASSWORD: sonar
        volumes:
            - $SONAR_HOME/data:/opt/sonarqube/data
            - $SONAR_HOME/extensions:/opt/sonarqube/extensions
            - $SONAR_HOME/logs:/opt/sonarqube/logs
        ports:
            - "127.0.0.1:9000:9000"
        ulimits:
            nofile:
                soft: 65535
                hard: 65535
    db:
        image: postgres:12
        restart: unless-stopped
        environment:
            POSTGRES_USER: sonar
            POSTGRES_PASSWORD: sonar
        volumes:
            - $POSTGRESQL_HOME:/var/lib/postgresql
